---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
  labels:
    env: production

spec:
  accessModes:
   - ReadWriteMany
  resources:  
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dep
spec:
  selector:
    matchLabels:
      pod: httpd
      env: production

  replicas: 1
  template:
    metadata:
      labels:
        pod: httpd
        env: production

    spec:
      containers:
      - name: httpd
        image: jhagdu/httpd-web:v1

        ports:
        - containerPort: 80

        volumeMounts:
          - name: httpd-vol
            mountPath: /var/www/html/

      volumes:
      - name: httpd-vol
        persistentVolumeClaim:
          claimName: httpd-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  type: NodePort
  selector:
    pod: httpd

  ports:
  - port: 80
    protocol: TCP
    name: httpd-port

---