---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    env: production

spec:
  accessModes:
   - ReadWriteMany
  resources:  
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-dep
spec:
  selector:
    matchLabels:
      pod: php
      env: production

  replicas: 1
  template:
    metadata:
      labels:
        pod: php
        env: production

    spec:
      containers:
      - name: php
        image: jhagdu/php-web:v1

        ports:
        - containerPort: 80

        volumeMounts:
          - name: php-vol
            mountPath: /var/www/html/

      volumes:
      - name: php-vol
        persistentVolumeClaim:
          claimName: php-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  type: NodePort
  selector:
    pod: php

  ports:
  - port: 80
    protocol: TCP
    name: php-port

---