apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-dep
spec:
  selector:
    matchLabels:
      env: production

  replicas: 1
  template:
    metadata:
      labels:
        env: production

    spec:
      containers:
      - name: php
        image: jhagdu/php-web:v1

        ports:
        - containerPort: 80

        volumeMounts:
          - name: php-vol
            mountPath: /var/www/html/

      volumes:
      - name: php-vol
        persistentVolumeClaim:
          claimName: web-pvc
